
from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from google import genai
from google.genai import types


load_dotenv()


class AudioAwareValidator:
    """
    Validates a candidate ASR transcript against the original audio.

    The important distinction is that Gemini receives BOTH:
        1. The original audio
        2. The candidate transcript

    Therefore, the validation is audio-grounded rather than
    simply comparing one text against another.
    """

    PROMPT = """
    You are an expert ASR quality-control system.

    You are given:

    1. An audio recording containing spoken language.
    2. A candidate transcript generated by another speech-to-text model.

    Your task is to listen to the ACTUAL AUDIO and determine whether
    the candidate transcript accurately represents what was spoken.

    Do NOT assume the candidate transcript is correct.

    Compare the candidate transcript against the audio carefully.

    Pay particular attention to:

    - Incorrect words
    - Missing words
    - Extra words
    - Incorrect names
    - Incorrect numbers
    - Incorrect locations
    - Singular/plural differences
    - Verb tense differences
    - Homophones
    - Pronunciation ambiguity
    - Sentence-level omissions
    - Meaning-changing transcription errors

    Return ONLY valid JSON.

    Required JSON schema:

    {{
        "matches": true,
        "confidence": 0.95,
        "corrected_transcript": "Complete corrected transcript",
        "discrepancies": [
            {{
                "transcript_says": "incorrect text",
                "audio_actually_says": "correct text",
                "severity": "minor"
            }}
        ]
    }}

    Rules:

    - "matches" must be true only when the transcript accurately represents
    the spoken audio.
    - "confidence" must be a number between 0.0 and 1.0.
    - "corrected_transcript" must contain the complete corrected transcript.
    - "discrepancies" must be an array.
    - Use "minor" for small wording/transcription differences that do not
    materially change meaning.
    - Use "major" for errors that change meaning, names, numbers, locations,
    important terminology, or omit substantial speech.
    - If there are no discrepancies, return an empty array.
    - Do not invent corrections that cannot be supported by the audio.
    - Preserve the speaker's actual wording as closely as possible.
    - Do not rewrite the transcript stylistically.
    - Do not summarize the audio.

    Candidate transcript:

    {transcript}
    """

    def __init__(
        self,
        model_name: str = "gemini-3.7-flash",
        api_key: str | None = None,
    ) -> None:

        api_key = api_key or os.getenv("GOOGLE_API_KEY")

        if not api_key:
            raise RuntimeError(
                "GOOGLE_API_KEY is not configured. "
                "Set it in your environment or .env file."
            )

        self.client = genai.Client(api_key=api_key)
        self.model_name = model_name

    def validate(
        self,
        audio_path: str | Path,
        transcript: str,
    ) -> dict[str, Any]:

        audio_path = Path(audio_path)

        if not audio_path.exists():
            raise FileNotFoundError(
                f"Audio file does not exist: {audio_path}"
            )

        if not audio_path.is_file():
            raise ValueError(
                f"Audio path is not a file: {audio_path}"
            )

        if not transcript.strip():
            raise ValueError("Transcript cannot be empty.")

        prompt = self.PROMPT.format(
            transcript=transcript
        )

        # Upload the original audio.
        audio_file = self.client.files.upload(
            file=str(audio_path)
        )

        try:
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=[
                    audio_file,
                    prompt,
                ],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                ),
            )

            if not response.text:
                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            result = json.loads(response.text)

            self._validate_result_schema(result)

            return result

        finally:
            # Clean up uploaded file when possible.
            try:
                self.client.files.delete(
                    name=audio_file.name
                )
            except Exception:
                pass

    @staticmethod
    def _validate_result_schema(
        result: dict[str, Any],
    ) -> None:

        required_fields = {
            "matches",
            "confidence",
            "discrepancies",
        }

        missing = required_fields - result.keys()

        if missing:
            raise ValueError(
                f"Validator response missing fields: {missing}"
            )

        if not isinstance(result["matches"], bool):
            raise ValueError(
                "'matches' must be a boolean."
            )

        confidence = result["confidence"]

        if not isinstance(confidence, (int, float)):
            raise ValueError(
                "'confidence' must be numeric."
            )

        if not 0.0 <= confidence <= 1.0:
            raise ValueError(
                "'confidence' must be between 0.0 and 1.0."
            )

        if not isinstance(result["discrepancies"], list):
            raise ValueError(
                "'discrepancies' must be an array."
            )

        for discrepancy in result["discrepancies"]:

            required = {
                "transcript_says",
                "audio_actually_says",
                "severity",
            }

            missing = required - discrepancy.keys()

            if missing:
                raise ValueError(
                    f"Invalid discrepancy. Missing: {missing}"
                )

            if discrepancy["severity"] not in {
                "minor",
                "major",
            }:
                raise ValueError(
                    "Discrepancy severity must be "
                    "'minor' or 'major'."
                )
